# Generated by Django 4.2.13 on 2024-06-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_activity', '0003_voicemodality_typingmonitormodality_swipemodality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
