# Generated by Django 4.2.13 on 2024-06-24 10:05

import adl_activity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_activity', '0004_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicemodality',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=adl_activity.models.user_directory_path),
        ),
    ]
